spring:
  application:
    name: chromamon-analysis-service
  datasource:
    url: jdbc:postgresql://localhost:5433/${DATABASE_NAME}?currentSchema=analysis
    username: ${DATABASE_USER}
    password: ${DATABASE_PASS}
    driver-class-name: org.postgresql.Driver
  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 100

springdoc:
  swagger-ui:
    path: /docs
    operationsSorter: method
    tagsSorter: alpha
  api-docs:
    path: /api-docs
    version: openapi_3_0

jwt:
  secret-key: ${JWT_SECRET_KEY}
