version: '3.8'
services:
  data-ingestion:
    image: chroma-data-ingestion:latest
    build:
      context: ../chroma-data-ingestion
    ports:
      - "5001:5001"

  analysis-service:
    image: chroma-analysis-service:latest
    build:
      context: ../chroma-analysis-service
    ports:
      - "8080:8080"

  transformer-management:
    image: chroma-transformer-management:latest
    build:
      context: ../chroma-transformer-management
    ports:
      - "8081:8081"

  report-service:
    image: chroma-report-service:latest
    build:
      context: ../chroma-report-service
    ports:
      - "5002:5002"

  mongodb:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: chroma
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  mongodb-data:
  postgres-data:
