package com.monolithic.chromamon.login.infrastructure.web;

import com.monolithic.chromamon.login.application.service.LoginService;
import com.monolithic.chromamon.shared.domain.security.SwaggerConstants;
import com.monolithic.chromamon.shared.infrastructure.web.GlobalExceptionHandler;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.enums.ParameterStyle;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.servers.Server;
import jakarta.validation.constraints.NotBlank;
import lombok.RequiredArgsConstructor;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

/**
 * Controller for checking the token validation.
 */
@RestController
@RequestMapping("/api/v1/auth")
@RequiredArgsConstructor
public class CheckTokenController {

   private final LoginService loginService;

   /**
    * Endpoint for checking the JWT token validation.
    *
    * @param token the string JWT token.
    * @return true or false depending on the validation.
    */
   @Operation(
      summary = "Validate the user token",
      description = "Checks if the user using the application has a valid token",
      operationId = "validateToken",
      method = SwaggerConstants.METHOD_POST,
      tags = {
         SwaggerConstants.TAG_AUTHENTICATION
      },
      parameters = {
         @Parameter(
            name = "token",
            in = ParameterIn.QUERY,
            description = "The string value of the JWT token generated by the application.",
            required = true,
            style = ParameterStyle.FORM,
            schema = @Schema(
               implementation = String.class,
               type = SwaggerConstants.STRING
            ),
            example = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"
         )
      },
      responses = {
         @ApiResponse(
            responseCode = "200",
            description = "Successfully checked the token validation",
            content = @Content(
               mediaType = MediaType.APPLICATION_JSON_VALUE,
               schema = @Schema(
                  implementation = Boolean.class
               ),
               examples = {
                  @ExampleObject(
                     name = "Valid token",
                     description = "The returned boolean if the token is valid",
                     value = "true"
                  ),
                  @ExampleObject(
                     name = "Invalid token",
                     description = "The returned boolean if the token is not valid",
                     value = "false"
                  )
               }
            )
         ),
         @ApiResponse(
            responseCode = "500",
            description = "Some error occurred while validating the token (probably the token was not sent), contact the IT",
            content = @Content(
               mediaType = MediaType.APPLICATION_JSON_VALUE,
               schema = @Schema(
                  implementation = GlobalExceptionHandler.ErrorResponse.class,
                  example = """
                     {
                         "timestamp": "2025-08-29T20:13:30.565819877",
                         "status": 500,
                         "error": "Internal Server Error",
                         "message": "Internal Server Error",
                         "path": "/api/v1/auth/validate",
                         "validationErrors": null
                     }
                     """
               )
            )
         )
      },
      servers = {
         @Server(
            url = SwaggerConstants.SERVER_LOCALHOST
         )
      }
   )
   @PostMapping(
      value = "/validate",
      produces = MediaType.APPLICATION_JSON_VALUE)
   public ResponseEntity<Boolean> validateToken(
      @RequestParam
      @NotBlank(message = "")
      String token) {
      boolean isValid = loginService.validateToken(token);
      return ResponseEntity.ok(isValid);
   }
}
