apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
  namespace: chroma
spec:
  containers:
    - name: debug-container
      image: nicolaka/netshoot # Imagem com ferramentas de rede
      command: [ "/bin/sh" ]
      stdin: true
      tty: true

