spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: Chromamon
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 30000
      leak-detection-threshold: 60000

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-on-migrate: true
    clean-disabled: true

  management:
    endpoints:
      web:
        exposure:
          include: health,info,metrics,prometheus
    endpoint:
      health:
        show-details: always
    metrics:
      tags:
        application: ${spring.application.name}

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

  quartz:
    jobStore:
      dataSource: quartzDataSource
    dataSource:
      quartzDataSource:
        driver: org.postgresql.Driver
        URL: jdbc:postgresql://localhost:5433/${PG_DATABASE_NAME}
        user: ${PG_DATABASE_USER}
        password: ${PG_DATABASE_PASS}

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET}
      expiration: ${JWT_EXPIRATION:86400}
      auth-scheme: ${JWT_AUTH_SCHEME:Bearer}

  chromatography:
    analysis:
      max-file-size: 50MB
      allowed-file-types: xlsx,csv,txt
      temp-dir: ${TEMP_DIR:/tmp/chromatography}

    reports:
      output-dir: ${REPORTS_DIR:/tmp/reports}
      template-dir: classpath:/reports/templates
      max-retention-days: 30

    transformer:
      default-oil-type: mineral
      max-age-years: 50

external-apis:
  # Add external APIs here
  weather: https://archive-api.open-meteo.com/v1/archive

server:
  port: 8443
  ssl:
    key-store-type: PKCS12
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  compression:
    enabled: true
    mime-types: text/html,text/css,application/javascript,application/json
  error:
    whitelabel:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env
      base-path: /actuator
  endpoint:
    health:
      show-details: when_authorized
      probes:
        enabled: true
    metrics:
      access: unrestricted
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5,0.9,0.95,0.99

  info:
    env:
      enabled: true
    build:
      enabled: true
    git:
      enabled: true
      mode: full
  prometheus:
    metrics:
      export:
        enabled: true
        step: 60s

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    display-request-duration: true
    show-actuator: true
  show-actuator: true
  group-configs:
    - group: 'analysis'
      paths-to-match: '/api/v1/analyses/**'
      display-name: 'Chromatographic analyses'
    - group: 'transformers'
      paths-to-match: '/api/v1/transformers/**'
      display-name: 'Transformers'
    - group: 'diagnostics'
      paths-to-match: '/api/v1/diagnostics/**'
      display-name: 'Diagnostics'
    - group: 'reports'
      paths-to-match: '/api/v1/reports/**'
      display-name: 'Reports'
    - group: 'auth'
      paths-to-match: '/api/v1/auth/**'
      display-name: 'Authentication'